# syntax=docker/dockerfile:1

FROM python:3.11-slim-bookworm

WORKDIR /hestia

COPY requirements.txt requirements.txt

RUN apt-get update && apt-get install gcc -y
RUN pip3 install -r requirements.txt

COPY secrets.py secrets.py
COPY hestia.py hestia.py
COPY bot.py bot.py

ARG APP_VERSION
RUN sed -i "s/APP_VERSION = ''/APP_VERSION = '$APP_VERSION'/g" hestia.py

CMD ["python3", "bot.py"]
