# syntax=docker/dockerfile:1

FROM python:3.8-slim-buster

ARG APP_VERSION

WORKDIR /hestia

COPY requirements.txt requirements.txt

RUN pip3 install -r requirements.txt

COPY secrets.py secrets.py
COPY hestia.py hestia.py
COPY bot.py bot.py

RUN sed -i "s/APP_VERSION = None/APP_VERSION = $APP_VERSION/g" hestia.py

CMD ["python3", "bot.py"]
