# syntax=docker/dockerfile:1

FROM python:3.8-slim-buster

WORKDIR /hestia

COPY requirements.txt requirements.txt

RUN pip3 install -r requirements.txt

COPY secrets.py secrets.py
COPY targets.py targets.py
COPY bot.py bot.py

CMD ["python3", "bot.py"]

