networks:
  hestia-network:
    name: hestia-network

volumes:
  hestia-database-volume:
    name: hestia-database-volume

x-scraper: &scraper-base
  healthcheck:
    test: pgrep cron || exit 1
    start_period: 5s
  image: wtfloris/hestia-scraper:latest
  init: true
  networks:
    - hestia-network
  restart: unless-stopped
  volumes:
    - /root/hestia/data:/data
  working_dir: /scraper

services:
  hestia-bot:
    container_name: hestia-bot
    healthcheck:
      test: cat /proc/1/cmdline || exit 1
      start_period: 5s
    image: wtfloris/hestia-bot:latest
    networks:
      - hestia-network
    restart: unless-stopped
    volumes:
      - /root/hestia/data:/data
    working_dir: /hestia

  hestia-scraper-maintenance:
    <<: *scraper-base
    container_name: hestia-scraper-maintenance

  hestia-scraper-123wonen:
    <<: *scraper-base
    container_name: hestia-scraper-123wonen
    environment:
      - AGENCY=123wonen

  hestia-scraper-alliantie:
    <<: *scraper-base
    container_name: hestia-scraper-alliantie
    environment:
      - AGENCY=alliantie

  hestia-scraper-atta:
    <<: *scraper-base
    container_name: hestia-scraper-atta
    environment:
      - AGENCY=atta

  hestia-scraper-easylease:
    <<: *scraper-base
    container_name: hestia-scraper-easylease
    environment:
      - AGENCY=easylease

  hestia-scraper-entree:
    <<: *scraper-base
    container_name: hestia-scraper-entree
    environment:
      - AGENCY=entree

  hestia-scraper-funda:
    <<: *scraper-base
    container_name: hestia-scraper-funda
    environment:
      - AGENCY=funda

  hestia-scraper-hexia-dewoningzoeker:
    <<: *scraper-base
    container_name: hestia-scraper-hexia-dewoningzoeker
    environment:
      - AGENCY=hexia_dewoningzoeker

  hestia-scraper-hexia-frieslandhuurt:
    <<: *scraper-base
    container_name: hestia-scraper-hexia-frieslandhuurt
    environment:
      - AGENCY=hexia_frieslandhuurt

  hestia-scraper-hexia-hollandrijnland:
    <<: *scraper-base
    container_name: hestia-scraper-hexia-hollandrijnland
    environment:
      - AGENCY=hexia_hollandrijnland

  hestia-scraper-hexia-klikvoorwonen:
    <<: *scraper-base
    container_name: hestia-scraper-hexia-klikvoorwonen
    environment:
      - AGENCY=hexia_klikvoorwonen

  hestia-scraper-hexia-mosaic-plaza:
    <<: *scraper-base
    container_name: hestia-scraper-hexia-mosaic-plaza
    environment:
      - AGENCY=hexia_mosaic-plaza

  hestia-scraper-hexia-noordveluwe:
    <<: *scraper-base
    container_name: hestia-scraper-hexia-noordveluwe
    environment:
      - AGENCY=hexia_noordveluwe

  hestia-scraper-hexia-oostwestwonen:
    <<: *scraper-base
    container_name: hestia-scraper-hexia-oostwestwonen
    environment:
      - AGENCY=hexia_oostwestwonen

  hestia-scraper-hexia-thuisindeachterhoek:
    <<: *scraper-base
    container_name: hestia-scraper-hexia-thuisindeachterhoek
    environment:
      - AGENCY=hexia_thuisindeachterhoek

  hestia-scraper-hexia-thuisinlimburg:
    <<: *scraper-base
    container_name: hestia-scraper-hexia-thuisinlimburg
    environment:
      - AGENCY=hexia_thuisinlimburg

  hestia-scraper-hexia-thuispoort:
    <<: *scraper-base
    container_name: hestia-scraper-hexia-thuispoort
    environment:
      - AGENCY=hexia_thuispoort

  hestia-scraper-hexia-thuispoortstudenten:
    <<: *scraper-base
    container_name: hestia-scraper-hexia-thuispoortstudenten
    environment:
      - AGENCY=hexia_thuispoortstudenten

  hestia-scraper-hexia-woninginzicht:
    <<: *scraper-base
    container_name: hestia-scraper-hexia-woninginzicht
    environment:
      - AGENCY=hexia_woninginzicht

  hestia-scraper-hexia-wooniezie:
    <<: *scraper-base
    container_name: hestia-scraper-hexia-wooniezie
    environment:
      - AGENCY=hexia_wooniezie

  hestia-scraper-hexia-woonnethaaglanden:
    <<: *scraper-base
    container_name: hestia-scraper-hexia-woonnethaaglanden
    environment:
      - AGENCY=hexia_woonnethaaglanden

  hestia-scraper-hexia-zuidwestwonen:
    <<: *scraper-base
    container_name: hestia-scraper-hexia-zuidwestwonen
    environment:
      - AGENCY=hexia_zuidwestwonen

  hestia-scraper-hoekstra:
    <<: *scraper-base
    container_name: hestia-scraper-hoekstra
    environment:
      - AGENCY=hoekstra

  hestia-scraper-krk:
    <<: *scraper-base
    container_name: hestia-scraper-krk
    environment:
      - AGENCY=krk

  hestia-scraper-maxxhuren:
    <<: *scraper-base
    container_name: hestia-scraper-maxxhuren
    environment:
      - AGENCY=maxxhuren

  hestia-scraper-nmg:
    <<: *scraper-base
    container_name: hestia-scraper-nmg
    environment:
      - AGENCY=nmg

  hestia-scraper-ooms:
    <<: *scraper-base
    container_name: hestia-scraper-ooms
    environment:
      - AGENCY=ooms

  hestia-scraper-rebo:
    <<: *scraper-base
    container_name: hestia-scraper-rebo
    environment:
      - AGENCY=rebo

  hestia-scraper-roofz:
    <<: *scraper-base
    container_name: hestia-scraper-roofz
    environment:
      - AGENCY=roofz

  hestia-scraper-vanderlinden:
    <<: *scraper-base
    container_name: hestia-scraper-vanderlinden
    environment:
      - AGENCY=vanderlinden

  hestia-scraper-vbo:
    <<: *scraper-base
    container_name: hestia-scraper-vbo
    environment:
      - AGENCY=vbo

  hestia-scraper-vbt:
    <<: *scraper-base
    container_name: hestia-scraper-vbt
    environment:
      - AGENCY=vbt

  hestia-scraper-vesteda:
    <<: *scraper-base
    container_name: hestia-scraper-vesteda
    environment:
      - AGENCY=vesteda

  hestia-scraper-woningnet-almere:
    <<: *scraper-base
    container_name: hestia-scraper-woningnet-almere
    environment:
      - AGENCY=woningnet_almere

  hestia-scraper-woningnet-amsterdam:
    <<: *scraper-base
    container_name: hestia-scraper-woningnet-amsterdam
    environment:
      - AGENCY=woningnet_amsterdam

  hestia-scraper-woningnet-eemvallei:
    <<: *scraper-base
    container_name: hestia-scraper-woningnet-eemvallei
    environment:
      - AGENCY=woningnet_eemvallei

  hestia-scraper-woningnet-gooienvecht:
    <<: *scraper-base
    container_name: hestia-scraper-woningnet-gooienvecht
    environment:
      - AGENCY=woningnet_gooienvecht

  hestia-scraper-woningnet-groningen:
    <<: *scraper-base
    container_name: hestia-scraper-woningnet-groningen
    environment:
      - AGENCY=woningnet_groningen

  hestia-scraper-woningnet-huiswaarts:
    <<: *scraper-base
    container_name: hestia-scraper-woningnet-huiswaarts
    environment:
      - AGENCY=woningnet_huiswaarts

  hestia-scraper-woningnet-middenholland:
    <<: *scraper-base
    container_name: hestia-scraper-woningnet-middenholland
    environment:
      - AGENCY=woningnet_middenholland

  hestia-scraper-woningnet-mijnwoonservice:
    <<: *scraper-base
    container_name: hestia-scraper-woningnet-mijnwoonservice
    environment:
      - AGENCY=woningnet_mijnwoonservice

  hestia-scraper-woningnet-utrecht:
    <<: *scraper-base
    container_name: hestia-scraper-woningnet-utrecht
    environment:
      - AGENCY=woningnet_utrecht

  hestia-scraper-woningnet-woongaard:
    <<: *scraper-base
    container_name: hestia-scraper-woningnet-woongaard
    environment:
      - AGENCY=woningnet_woongaard

  hestia-scraper-woningnet-woonkeus:
    <<: *scraper-base
    container_name: hestia-scraper-woningnet-woonkeus
    environment:
      - AGENCY=woningnet_woonkeus

  hestia-scraper-woonin:
    <<: *scraper-base
    container_name: hestia-scraper-woonin
    environment:
      - AGENCY=woonin

  hestia-scraper-woonmatchwaterland:
    <<: *scraper-base
    container_name: hestia-scraper-woonmatchwaterland
    environment:
      - AGENCY=woonmatchwaterland

  hestia-database:
    container_name: hestia-database
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 10s
    image: postgres:15
    networks:
      - hestia-network
    ports:
      - "127.0.0.1:5432:5432"
    restart: unless-stopped
    volumes:
      - hestia-database-volume:/var/lib/postgresql/data

  hestia-web:
    container_name: hestia-web
    image: wtfloris/hestia-web:latest
    networks:
      - hestia-network
    ports:
      - "19191:5050"
    restart: unless-stopped
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - SECRET_KEY=${SECRET_KEY}
      - BREVO_API_KEY=${BREVO_API_KEY}
      - FROM_EMAIL=${FROM_EMAIL}
      - BASE_URL=${BASE_URL}
      - LOG_FORMAT=${LOG_FORMAT:-plain}
